### ISSUE TITLE
[Enhancement] add css class to imported text

### ISSUE THREAD

**Issue by Gabri** [kuchejak/obsidian-bible-linker-plugin#55]
I couldn't find in the html of the rendered text any classes, that sound strange to me, it could be useful to have in this way we can easely stylize them.
Even better if that or those classes to attach could be set in the settings of the plugin.
What do you think?

Thanks

**Comment by kuchejak** [comment]
Hi, are you talking about the copy command? The output is just a plain text, not sure how CSS classes should be applied to it, without wrapping it in a HTML tag.

If you want to apply custom styles, I recommend using the [Obsidian callouts feature](https://help.obsidian.md/Editing+and+formatting/Callouts). 

For example those are my personal settings using [!bible] callout with custom styling.

<img width="790" alt="Image" src="https://github.com/user-attachments/assets/1e1606fa-9529-450c-a42f-7862d8ce6da8" />

My css:
```css

.callout[data-callout="bible"] {
    --callout-color: 130, 100, 73;
    --callout-icon: book-open-text;
}

/* Default text color for light mode */
.theme-light .callout[data-callout="bible"] h1,
.theme-light .callout[data-callout="bible"] h2,
.theme-light .callout[data-callout="bible"] h3,
.theme-light .callout[data-callout="bible"] h4,
.theme-light .callout[data-callout="bible"] h5,
.theme-light .callout[data-callout="bible"] a {
  color: black;
  text-decoration: none;
}

/* Text color for dark mode */
.theme-dark .callout[data-callout="bible"] h1,
.theme-dark .callout[data-callout="bible"] h2,
.theme-dark .callout[data-callout="bible"] h3,
.theme-dark .callout[data-callout="bible"] h4,
.theme-dark .callout[data-callout="bible"] h5,
.theme-dark .callout[data-callout="bible"] a {
  color: white;
  text-decoration: none;
}
```
